# Generated by Django 4.2.3 on 2023-07-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='conform_password',
            new_name='c_p',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
    ]
