# Generated by Django 4.2.3 on 2023-07-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_conform_password_user_c_p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='c_p',
        ),
    ]
