# Generated by Django 4.2.3 on 2023-07-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_user_c_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
