# Generated by Django 4.2.3 on 2023-07-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_delete_employee_user_firstname_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EMP',
        ),
    ]
